#! /bin/bash
#
#   If you have a very virgin ubuntu, you may need to ensure these packages are present
#   for some of the study7 work.
#
#   this may be a moving target as we find more things we need
#
#   perhaps these too:  libgfortran3 (for casa6)

sudo apt update
sudo apt install -y tcsh autoconf make emacs25-nox dot awscli nfs-common
sudo apt install -y libxft2 libsm6 libxi6 libxrandr2 libxfixes3 libxcursor1 libxinerama1 libglvnd-dev x11-xkb-utils
sudo apt install -y libssl-dev libsqlite3-dev
sudo apt install -u imagemagick


