#! /bin/csh -f
#
#   this may be a moving target as we find more things we need
#

sudo apt update
sudo apt install tcsh autoconf make emacs25-nox dot
sudo apt install libxft2 libsm6 libxi6 libxrandr2 libxfixes3 libxcursor1 libxinerama1 libglvnd-dev 
