#! /bin/csh -f
#
#  Install an anaconda3 python for astroquery.alma, and optionally casa6
#

            # 670MB
set mc3   = https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh
set mc3   = https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
set msh   = $mc3:t
set dir   = `pwd`/anaconda3
set wget  = wget
set casa6 = 0

# you better know what you are doing here
foreach arg ($*)
  set $arg
end

if (! -e $msh) $wget $mc3
bash $msh -b -p $dir

setenv PATH "$dir/bin:$PATH"

conda update -y conda
pip install --upgrade pip

echo "set path = ($dir/bin "'$path); rehash'  >> python_start.csh
echo "export PATH=${dir}/bin:"'$PATH'         >> python_start.sh

# https://casa.nrao.edu/casadocs/casa-5.6.0/introduction/casa6-installation-and-usage
if ($casa6) then
  echo "pip install casatools and casatasks... this will download 740MB"
  echo "  conda install -y python=3.6.x  (make sure it's the latest)"
  if (1) then
    #conda install -y python=3.6.8
    conda install -y python=3.6.10
  else
    # From gpopping (worked for him)
    conda create --name python36 python=3.6 -y
    #conda activate python36
    # this claimed i needed to "conda init bash" but this screws up my .bashrc file, i'm not happy
    source activate python36
  endif
  if (0) then
    echo CASA6: standard released version
    pip install --extra-index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple casatools
    pip install --extra-index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple casatasks
  else
    echo CASA6: pre-release versions
    pip install --extra-index-url https://casa-pip.nrao.edu:443/repository/pypi-group/simple casatools
    pip install --extra-index-url https://casa-pip.nrao.edu:443/repository/pypi-group/simple casatasks
  endif
  
endif

exit 0


# pip install astroquery
# conda -c astropy astroquery

# install the latest (ALMA is broken in pip/conda, it's too old)
if (-d astroquery) then
  source python_start.csh
  cd astroquery
  python setup.py install
else if (1) then
  source python_start.csh
  git clone https://github.com/astropy/astroquery
  cd astroquery
  python setup.py install
else
  pip install --upgrade --pre astroquery
endif  
