#! /bin/csh -f
#


set mc3 = https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
set msh = $mc3:t
set dir = `pwd`/miniconda3

if (! -e $msh) wget $mc3
bash $msh -b -p $dir

setenv PATH "$dir/bin:$PATH"

which conda
which pip

conda install -y ipython numpy scipy matplotlib notebook jupyter astropy

echo "set path = ($dir/bin "'$path); rehash'  >> python_start.csh
echo "export PATH=${dir}/bin:"'$PATH'         >> python_start.sh


# pip install astroquery
# conda -c astropy astroquery

# install the latest (ALMA is broken in pip/conda, it's too old)
if (0) then
  source python_start.csh
  git clone https://github.com/astropy/astroquery
  cd astroquery
  python setup.py install
else
  pip install --upgrade --pre astroquery
endif  
