#! /bin/csh -f
#

set qac = `pwd`/QAC

if (! -e QAC) git clone https://github.com/teuben/QAC

cd QAC/casa
./install_casa
source casa_start.csh
cp casa_start.csh casa_start.sh ../..

cd ..

casa-config --version

if (! -e ~/.casa/QAC) then
    make data
    make install
    cd ~/.casa
    ln -s $qac
    cd $qac/test
    ln -sf ../data/M100_TP_CO_cube.bl.image
    ln -sf ../data/M100_aver_12.ms
    ln -sf ../data/M100_aver_7.ms
else
    echo You already have a QAC symlink.... cannot continue this way
endif
