#! /usr/bin/env bash
#

rm -rf admit2

git clone https://github.com/astroumd/admit admit2
cd admit2
./configure --with-casa-root=/n/astromake/opt/casa/casa-pipeline-release-5.6.2-2.el7
source admit_start.sh

make bench WGET=wgetc


echo Done with admit2
