#! /usr/bin/env bash
#

rm -rf admit361

git clone https://github.com/astroumd/admit admit361
cd admit361
git checkout python3

# could also use .. if local build
../casa6install.sh REL=0 ADMIT=0
#git clone https://github.com/teuben/study7
#study7/casa6install.sh REL=0 ADMIT=0

source python_start.sh
pip install -e .

make bench36
