#! /usr/bin/env python
#
#
#  Usage:  test_alma1 [project_code]
#
#  Warning: Gets all the data, including the potentially large asdm files
#           See test_alma2 for getting just the product tar files
#
#  Typical errors:
#  requests.exceptions.ConnectionError: HTTPSConnectionPool(host='almascience.nrao.edu', port=443): Read timed out.
#  urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))


import os, sys
import numpy as np
from astroquery.alma import Alma


pid = '2016.1.00004.S'    # nice smallish project
ids = None
if len(sys.argv) > 1: pid = sys.argv[1]
if len(sys.argv) > 2: ids = int(sys.argv[2])

print("pid=%s" % pid)
print("ids=%s" % repr(ids))
print("")
print("Once you see    Staging files... [astroquery.alma.core]")
print("Followed by a line printing a . every now and then, abort this script, as it runs fine")
print("")


pwd = os.getcwd() + '/data'
os.system('mkdir -p %s' % pwd)

alma = Alma()

data = alma.query(payload={'project_code':pid},science=True,public=True)
alma.cache_location = pwd
uids = np.unique(data['Member ous id'])
print("For project code %s found:" % pid)
print(uids)
if ids != None:
    print("Only using %s" % uids[ids])
    uids = [uids[ids]]
link_list = alma.stage_data(uids)
print(link_list['size'].sum())
alma.retrieve_data_from_uid(uids)

