#! /usr/bin/env python
#
#  during some testing stages this script may fail, when python is used,
#  but runs ok when ipython is used. go figure

# system
import os, sys
import numpy as np

# casa
try:
    import casatasks as ct
    import casatools
    ia = casatools.image()
except:
    print("failing to import casatasks/tools .... try running it through ipython instead")
    sys.exit(0)

#
print("Testing casa6 with ia.maketestimage()")

# ensure directory exists
pwd = os.getcwd() + '/data'
os.system('mkdir -p %s' % pwd)

# casa
ia.maketestimage('data/test6.im',overwrite=True)
ct.imhead('data/test6.im')
s0=ia.statistics()
ia.close()

#
print(s0)
