#! /usr/bin/env python
#

import os, sys
import numpy as np
from astroquery.alma import Alma


pid = '2016.1.00324.L'
usr = None
if len(sys.argv) > 1: pid = sys.argv[1]

pwd = os.getcwd() + '/data'
os.system('mkdir -p %s' % pwd)

alma = Alma()

data = alma.query(payload={'project_code':pid},science=True,public=True)
alma.cache_location = pwd
if usr != None:
    alma.login(usr,store_password=True)
uids = np.unique(data['Member ous id'])
print("For project code %s found:" % pid)
print(uids)
link_list = alma.stage_data(uids)
print(link_list['size'].sum())
alma.retrieve_data_from_uid(uids[0])

