#! /usr/bin/env python
#

import os, sys, glob

pid = '2018.1.01115.S'
uid = 'uid://A001/X133f/X19c'

if len(sys.argv) > 1: pid = sys.argv[1]
if len(sys.argv) > 2: uid = sys.argv[2]


uida = uid.split('/')
tar  = '%s_uid___%s_%s_%s_001_of_001.tar' % (pid, uida[2],uida[3],uida[4])
sous = 'science_goal.uid___%s_%s_%s' % (uida[2],uida[3],uida[4])

testdir = '%s/%s' % (pid,sous)

# if not exist
#cmd = 'tar xf %s' % tar
#os.system(cmd)

# this better exist, our test case

testfile = '%s/%s/*/*/product/member.uid___*.Ref_*.spw16.cube.I.pbcor.fits' % (pid,sous)


test = glob.glob(testfile)

if len(test) == 1:
    pbcor = test[0]
    pdir  = pbcor[:pbcor.rfind('/')]
    print('pdir: ',pbcor)
    print('root: ',pbcor[:-11])
    
