#! /usr/bin/env python
#
#
#
# uid://A001/X133f/X196 2018.1.01115.S_uid___A001_X133f_X196_001_of_001.tar -> science_goal.uid___A001_X133f_X194/
# uid://A001/X133f/X19a 2018.1.01115.S_uid___A001_X133f_X19a_001_of_001.tar    science_goal.uid___A001_X133f_X198/
# uid://A001/X133f/X19e 2018.1.01115.S_uid___A001_X133f_X19e_001_of_001.tar    science_goal.uid___A001_X133f_X19c/
# uid://A001/X133f/X1a2 2018.1.01115.S_uid___A001_X133f_X1a2_001_of_001.tar    science_goal.uid___A001_X133f_X1a0/


import os, sys, glob

pid = '2018.1.01115.S'
pbcor = 'member.uid___*.Ref_*.spw16.cube.I.pbcor.fits' 

if len(sys.argv) > 1: pid = sys.argv[1]

print("Processing project code %s" % pid)
print("Finding matching pbcor files with pattern '%s'" % pbcor)

testdirs = '%s/science_goal.*/group.*/member.*' % (pid)
test = glob.glob(testdirs)

pbcors = []
for t in test:
    testfile = '%s/product/%s' % (t,pbcor)
    test2 = glob.glob(testfile)
    for t2 in test2:
        pbcors.append(t2)

print("Found %d directories, with %d matching pbcor.fits files for processing" % (len(test),len(pbcors)))

for p in pbcors:
    # print(p)
    pdir  = p[:p.rfind('/')]
    pbcor = p[p.rfind('/')+1:]
    # print('pdir: ',pdir)
    # print('root: ',pbcor)
    cmd = 'cd %s ; runa1 %s' % (pdir,pbcor)
    print(cmd)
    os.system(cmd)

print("Finished processing %d pbcor.fits files" % (len(pbcors)))
    
